### PR TITLE
Update go-mobile@1.0.0-rc50

### PR DESCRIPTION
**Pull request by sanderpick**
I've gone over w/ a fine tooth comb, but no doubt there's something that'll need tweaking in here... so many little changes.

### CODE REVIEW

**Comment by andrewxhill** [comment]
I was just trying a quick integration test in advanced-boilerplate app. Is there much I need to change to make this work or should most of it operate as before? 

Just running the app with,

```javascript
this.textile = Textile
...
this.textile.setup(<config>)
...
```

and 

```javascript
this.events.addListener('newNodeState', (payload) => {
  console.log('state:', payload.state)
})
```

I see 

```
creating
creatingWallet
derivingAccount
```

then it stops.

**Comment by asutula** [comment]
To clarify that `pb` thing, I mean we should be able to export all model objects (both the generated pb objects and internal SDK objects) straight into the `Models` module and the re-export that `Models` module out of the main sdk module so that all the models are simple available like 
```import { IContact } from '@textile/react-native-sdk'```

**Comment by sanderpick** [comment]
Re: andrew, what needs to change... I don't know. I suspect the events stuff, I just updated scattered occurrences of strings that looked like old event names coming from the go-textile.

**Comment by andrewxhill** [comment]
it didn't appear to be an event, it _looked_ like `API.wallet.accountAt` linked above doesn't return

**Comment by sanderpick** [comment]
I was referring to your question, "is there much I need to change?"

**Comment by sanderpick** [comment]
@asutula I think that would work if we could do this:

```
export * from '@textile/go-mobile'
export * from './SDK'
```

But since we have the top-level enum problem, `pb` imports as an object. Maybe there's a way to use an additional namspace or something with `{ ...pb, ...sdk }` in the index somehow, but doesn't seem worth it to me. I'm gonna try and fix the enum issue on our own fork of protobufjs at some point.

**Comment by sanderpick** [comment]
Oop, I see what's up with the wallet account. One sec.

**Pull request merged**
