### PR TITLE
Updates sdk to use new token on registration method

### PR DESCRIPTION
**Pull request by carsonfarmer**
Based on rc-32 from textile-go. Depends on https://github.com/textileio/textile-go/pull/492.

### CODE REVIEW

**Comment by carsonfarmer** [comment]
Should be GTG with latest textile-go release. But don't update to this version on mobile yet.

**Comment by andrewxhill** [comment]
oop, hate to do this to you, but could you point this at andrew/sdk-v1 or hold until i merge that

**Comment by andrewxhill** [comment]
oh.. sorry, nm, you need this in the app sooner

**Comment by carsonfarmer** [comment]
Is it going to cause nasty merge/rebase conflicts for your work? We should probably get this in sooner rather than later... but it could wait...

**Comment by carsonfarmer** [comment]
Hey @andrewxhill take a look at this updated PR now. Should be pretty simple/straightforward...

**Comment by andrewxhill** [comment]
Looks like the method in `lib/Textile/index.ts` wasn't updated for `registerCafe`. there are a few different cases of it. just run `yarn test` and the ones I see will pop up.

**Pull request merged**
